### ISSUE TITLE
KeyError: 'akey'

### ISSUE THREAD

**Issue by zyonse** [falsidge/ruo#2]
After pasting my input code I'm getting this error in the console:

```
Traceback (most recent call last):
  File "/home/gzyonse/ruo/main.py", line 189, in <module>
    main()
  File "/home/gzyonse/ruo/main.py", line 164, in main
    c.activate()
  File "/home/gzyonse/ruo/main.py", line 90, in activate
    self.import_response(response)
  File "/home/gzyonse/ruo/main.py", line 75, in import_response
    self.akey = response["akey"]
KeyError: 'akey'
```

**Comment by falsidge** [comment]
#3

**Comment by raxod502** [comment]
I get the same error and stacktrace even using the latest commit (https://github.com/falsidge/ruo/commit/48c8c87496179fbc99a859caa3f392285d855384).
